# Generated by Django 3.2.16 on 2022-12-01 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sale.order')),
                ('item_no', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('product_total', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'order_line_item',
                'managed': False,
            },
        ),
    ]
